/* tslint:disable */
/* eslint-disable */
/**
 * (title)
 * A sample service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { PostAuthSignIn400Response, PostAuthSignIn500Response, SignInInput, SignUpValidationErrorResponse } from "../models/index";
import {
  PostAuthSignIn400ResponseFromJSON,
  PostAuthSignIn400ResponseToJSON,
  PostAuthSignIn500ResponseFromJSON,
  PostAuthSignIn500ResponseToJSON,
  SignInInputFromJSON,
  SignInInputToJSON,
  SignUpValidationErrorResponseFromJSON,
  SignUpValidationErrorResponseToJSON,
} from "../models/index";

export interface PostAuthSignInRequest {
  signInInput: SignInInput;
}

export interface PostAuthSignUpRequest {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  birthday?: Date;
  frontIdentification?: Blob;
  backIdentification?: Blob;
}

export interface PostAuthValidateSignUpRequest {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  birthday?: Date;
  frontIdentification?: Blob;
  backIdentification?: Blob;
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI {
  /**
   * Sign In
   */
  async postAuthSignInRaw(requestParameters: PostAuthSignInRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
    if (requestParameters["signInInput"] == null) {
      throw new runtime.RequiredError("signInInput", 'Required parameter "signInInput" was null or undefined when calling postAuthSignIn().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/auth/sign-in`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: SignInInputToJSON(requestParameters["signInInput"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Sign In
   */
  async postAuthSignIn(requestParameters: PostAuthSignInRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
    const response = await this.postAuthSignInRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Sign Up
   */
  async postAuthSignUpRaw(requestParameters: PostAuthSignUpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignUpValidationErrorResponse>> {
    if (requestParameters["firstName"] == null) {
      throw new runtime.RequiredError("firstName", 'Required parameter "firstName" was null or undefined when calling postAuthSignUp().');
    }

    if (requestParameters["lastName"] == null) {
      throw new runtime.RequiredError("lastName", 'Required parameter "lastName" was null or undefined when calling postAuthSignUp().');
    }

    if (requestParameters["email"] == null) {
      throw new runtime.RequiredError("email", 'Required parameter "email" was null or undefined when calling postAuthSignUp().');
    }

    if (requestParameters["password"] == null) {
      throw new runtime.RequiredError("password", 'Required parameter "password" was null or undefined when calling postAuthSignUp().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const consumes: runtime.Consume[] = [{ contentType: "multipart/form-data" }];
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes);

    let formParams: { append(param: string, value: any): any };
    let useForm = false;
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm;
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm;
    if (useForm) {
      formParams = new FormData();
    } else {
      formParams = new URLSearchParams();
    }

    if (requestParameters["firstName"] != null) {
      formParams.append("firstName", requestParameters["firstName"] as any);
    }

    if (requestParameters["lastName"] != null) {
      formParams.append("lastName", requestParameters["lastName"] as any);
    }

    if (requestParameters["email"] != null) {
      formParams.append("email", requestParameters["email"] as any);
    }

    if (requestParameters["password"] != null) {
      formParams.append("password", requestParameters["password"] as any);
    }

    if (requestParameters["birthday"] != null) {
      formParams.append("birthday", requestParameters["birthday"] as any);
    }

    if (requestParameters["frontIdentification"] != null) {
      formParams.append("frontIdentification", requestParameters["frontIdentification"] as any);
    }

    if (requestParameters["backIdentification"] != null) {
      formParams.append("backIdentification", requestParameters["backIdentification"] as any);
    }

    const response = await this.request(
      {
        path: `/auth/sign-up`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => SignUpValidationErrorResponseFromJSON(jsonValue));
  }

  /**
   * Sign Up
   */
  async postAuthSignUp(requestParameters: PostAuthSignUpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignUpValidationErrorResponse> {
    const response = await this.postAuthSignUpRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Validate Sign Up
   */
  async postAuthValidateSignUpRaw(
    requestParameters: PostAuthValidateSignUpRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SignUpValidationErrorResponse>> {
    if (requestParameters["firstName"] == null) {
      throw new runtime.RequiredError("firstName", 'Required parameter "firstName" was null or undefined when calling postAuthValidateSignUp().');
    }

    if (requestParameters["lastName"] == null) {
      throw new runtime.RequiredError("lastName", 'Required parameter "lastName" was null or undefined when calling postAuthValidateSignUp().');
    }

    if (requestParameters["email"] == null) {
      throw new runtime.RequiredError("email", 'Required parameter "email" was null or undefined when calling postAuthValidateSignUp().');
    }

    if (requestParameters["password"] == null) {
      throw new runtime.RequiredError("password", 'Required parameter "password" was null or undefined when calling postAuthValidateSignUp().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const consumes: runtime.Consume[] = [{ contentType: "multipart/form-data" }];
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes);

    let formParams: { append(param: string, value: any): any };
    let useForm = false;
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm;
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm;
    if (useForm) {
      formParams = new FormData();
    } else {
      formParams = new URLSearchParams();
    }

    if (requestParameters["firstName"] != null) {
      formParams.append("firstName", requestParameters["firstName"] as any);
    }

    if (requestParameters["lastName"] != null) {
      formParams.append("lastName", requestParameters["lastName"] as any);
    }

    if (requestParameters["email"] != null) {
      formParams.append("email", requestParameters["email"] as any);
    }

    if (requestParameters["password"] != null) {
      formParams.append("password", requestParameters["password"] as any);
    }

    if (requestParameters["birthday"] != null) {
      formParams.append("birthday", requestParameters["birthday"] as any);
    }

    if (requestParameters["frontIdentification"] != null) {
      formParams.append("frontIdentification", requestParameters["frontIdentification"] as any);
    }

    if (requestParameters["backIdentification"] != null) {
      formParams.append("backIdentification", requestParameters["backIdentification"] as any);
    }

    const response = await this.request(
      {
        path: `/auth/validate-sign-up`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => SignUpValidationErrorResponseFromJSON(jsonValue));
  }

  /**
   * Validate Sign Up
   */
  async postAuthValidateSignUp(requestParameters: PostAuthValidateSignUpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignUpValidationErrorResponse> {
    const response = await this.postAuthValidateSignUpRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
