/* tslint:disable */
/* eslint-disable */
/**
 * (title)
 * A sample service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DeleteTodoResponse
 */
export interface DeleteTodoResponse {
  /**
   *
   * @type {number}
   * @memberof DeleteTodoResponse
   */
  code: number;
  /**
   *
   * @type {boolean}
   * @memberof DeleteTodoResponse
   */
  result: boolean;
}

/**
 * Check if a given object implements the DeleteTodoResponse interface.
 */
export function instanceOfDeleteTodoResponse(value: object): value is DeleteTodoResponse {
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("result" in value) || value["result"] === undefined) return false;
  return true;
}

export function DeleteTodoResponseFromJSON(json: any): DeleteTodoResponse {
  return DeleteTodoResponseFromJSONTyped(json, false);
}

export function DeleteTodoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteTodoResponse {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"],
    result: json["result"],
  };
}

export function DeleteTodoResponseToJSON(json: any): DeleteTodoResponse {
  return DeleteTodoResponseToJSONTyped(json, false);
}

export function DeleteTodoResponseToJSONTyped(value?: DeleteTodoResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    code: value["code"],
    result: value["result"],
  };
}
