/* tslint:disable */
/* eslint-disable */
/**
 * (title)
 * A sample service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Todo } from "./Todo";
import { TodoFromJSON, TodoFromJSONTyped, TodoToJSON, TodoToJSONTyped } from "./Todo";

/**
 *
 * @export
 * @interface FetchTodosResponse
 */
export interface FetchTodosResponse {
  /**
   *
   * @type {Array<Todo>}
   * @memberof FetchTodosResponse
   */
  todos: Array<Todo>;
}

/**
 * Check if a given object implements the FetchTodosResponse interface.
 */
export function instanceOfFetchTodosResponse(value: object): value is FetchTodosResponse {
  if (!("todos" in value) || value["todos"] === undefined) return false;
  return true;
}

export function FetchTodosResponseFromJSON(json: any): FetchTodosResponse {
  return FetchTodosResponseFromJSONTyped(json, false);
}

export function FetchTodosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchTodosResponse {
  if (json == null) {
    return json;
  }
  return {
    todos: (json["todos"] as Array<any>).map(TodoFromJSON),
  };
}

export function FetchTodosResponseToJSON(json: any): FetchTodosResponse {
  return FetchTodosResponseToJSONTyped(json, false);
}

export function FetchTodosResponseToJSONTyped(value?: FetchTodosResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    todos: (value["todos"] as Array<any>).map(TodoToJSON),
  };
}
