/* tslint:disable */
/* eslint-disable */
/**
 * (title)
 * A sample service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PostAuthSignIn400Response
 */
export interface PostAuthSignIn400Response {
  /**
   *
   * @type {Array<string>}
   * @memberof PostAuthSignIn400Response
   */
  errors: Array<string>;
}

/**
 * Check if a given object implements the PostAuthSignIn400Response interface.
 */
export function instanceOfPostAuthSignIn400Response(value: object): value is PostAuthSignIn400Response {
  if (!("errors" in value) || value["errors"] === undefined) return false;
  return true;
}

export function PostAuthSignIn400ResponseFromJSON(json: any): PostAuthSignIn400Response {
  return PostAuthSignIn400ResponseFromJSONTyped(json, false);
}

export function PostAuthSignIn400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAuthSignIn400Response {
  if (json == null) {
    return json;
  }
  return {
    errors: json["errors"],
  };
}

export function PostAuthSignIn400ResponseToJSON(json: any): PostAuthSignIn400Response {
  return PostAuthSignIn400ResponseToJSONTyped(json, false);
}

export function PostAuthSignIn400ResponseToJSONTyped(value?: PostAuthSignIn400Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    errors: value["errors"],
  };
}
