/* tslint:disable */
/* eslint-disable */
/**
 * (title)
 * A sample service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PostAuthSignIn500Response
 */
export interface PostAuthSignIn500Response {
  /**
   *
   * @type {number}
   * @memberof PostAuthSignIn500Response
   */
  code: number;
  /**
   *
   * @type {string}
   * @memberof PostAuthSignIn500Response
   */
  message: string;
}

/**
 * Check if a given object implements the PostAuthSignIn500Response interface.
 */
export function instanceOfPostAuthSignIn500Response(value: object): value is PostAuthSignIn500Response {
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  return true;
}

export function PostAuthSignIn500ResponseFromJSON(json: any): PostAuthSignIn500Response {
  return PostAuthSignIn500ResponseFromJSONTyped(json, false);
}

export function PostAuthSignIn500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAuthSignIn500Response {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"],
    message: json["message"],
  };
}

export function PostAuthSignIn500ResponseToJSON(json: any): PostAuthSignIn500Response {
  return PostAuthSignIn500ResponseToJSONTyped(json, false);
}

export function PostAuthSignIn500ResponseToJSONTyped(value?: PostAuthSignIn500Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    code: value["code"],
    message: value["message"],
  };
}
