/* tslint:disable */
/* eslint-disable */
/**
 * (title)
 * A sample service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Todo } from "./Todo";
import { TodoFromJSON, TodoFromJSONTyped, TodoToJSON, TodoToJSONTyped } from "./Todo";

/**
 *
 * @export
 * @interface ShowTodoResponse
 */
export interface ShowTodoResponse {
  /**
   *
   * @type {Todo}
   * @memberof ShowTodoResponse
   */
  todo: Todo;
}

/**
 * Check if a given object implements the ShowTodoResponse interface.
 */
export function instanceOfShowTodoResponse(value: object): value is ShowTodoResponse {
  if (!("todo" in value) || value["todo"] === undefined) return false;
  return true;
}

export function ShowTodoResponseFromJSON(json: any): ShowTodoResponse {
  return ShowTodoResponseFromJSONTyped(json, false);
}

export function ShowTodoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowTodoResponse {
  if (json == null) {
    return json;
  }
  return {
    todo: TodoFromJSON(json["todo"]),
  };
}

export function ShowTodoResponseToJSON(json: any): ShowTodoResponse {
  return ShowTodoResponseToJSONTyped(json, false);
}

export function ShowTodoResponseToJSONTyped(value?: ShowTodoResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    todo: TodoToJSON(value["todo"]),
  };
}
