/* tslint:disable */
/* eslint-disable */
/**
 * (title)
 * A sample service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SignUpValidationError } from "./SignUpValidationError";
import { SignUpValidationErrorFromJSON, SignUpValidationErrorFromJSONTyped, SignUpValidationErrorToJSON, SignUpValidationErrorToJSONTyped } from "./SignUpValidationError";

/**
 *
 * @export
 * @interface SignUpValidationErrorResponse
 */
export interface SignUpValidationErrorResponse {
  /**
   *
   * @type {number}
   * @memberof SignUpValidationErrorResponse
   */
  code: number;
  /**
   *
   * @type {SignUpValidationError}
   * @memberof SignUpValidationErrorResponse
   */
  errors: SignUpValidationError;
}

/**
 * Check if a given object implements the SignUpValidationErrorResponse interface.
 */
export function instanceOfSignUpValidationErrorResponse(value: object): value is SignUpValidationErrorResponse {
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("errors" in value) || value["errors"] === undefined) return false;
  return true;
}

export function SignUpValidationErrorResponseFromJSON(json: any): SignUpValidationErrorResponse {
  return SignUpValidationErrorResponseFromJSONTyped(json, false);
}

export function SignUpValidationErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpValidationErrorResponse {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"],
    errors: SignUpValidationErrorFromJSON(json["errors"]),
  };
}

export function SignUpValidationErrorResponseToJSON(json: any): SignUpValidationErrorResponse {
  return SignUpValidationErrorResponseToJSONTyped(json, false);
}

export function SignUpValidationErrorResponseToJSONTyped(value?: SignUpValidationErrorResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    code: value["code"],
    errors: SignUpValidationErrorToJSON(value["errors"]),
  };
}
