/* tslint:disable */
/* eslint-disable */
/**
 * (title)
 * A sample service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface StoreTodoValidationError
 */
export interface StoreTodoValidationError {
  /**
   *
   * @type {Array<string>}
   * @memberof StoreTodoValidationError
   */
  title?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof StoreTodoValidationError
   */
  content?: Array<string>;
}

/**
 * Check if a given object implements the StoreTodoValidationError interface.
 */
export function instanceOfStoreTodoValidationError(value: object): value is StoreTodoValidationError {
  return true;
}

export function StoreTodoValidationErrorFromJSON(json: any): StoreTodoValidationError {
  return StoreTodoValidationErrorFromJSONTyped(json, false);
}

export function StoreTodoValidationErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreTodoValidationError {
  if (json == null) {
    return json;
  }
  return {
    title: json["title"] == null ? undefined : json["title"],
    content: json["content"] == null ? undefined : json["content"],
  };
}

export function StoreTodoValidationErrorToJSON(json: any): StoreTodoValidationError {
  return StoreTodoValidationErrorToJSONTyped(json, false);
}

export function StoreTodoValidationErrorToJSONTyped(value?: StoreTodoValidationError | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    title: value["title"],
    content: value["content"],
  };
}
