/* tslint:disable */
/* eslint-disable */
/**
 * (title)
 * A sample service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { StoreTodoValidationError } from "./StoreTodoValidationError";
import { StoreTodoValidationErrorFromJSON, StoreTodoValidationErrorFromJSONTyped, StoreTodoValidationErrorToJSON, StoreTodoValidationErrorToJSONTyped } from "./StoreTodoValidationError";

/**
 *
 * @export
 * @interface StoreTodoResponse
 */
export interface StoreTodoResponse {
  /**
   *
   * @type {number}
   * @memberof StoreTodoResponse
   */
  code: number;
  /**
   *
   * @type {StoreTodoValidationError}
   * @memberof StoreTodoResponse
   */
  errors: StoreTodoValidationError;
}

/**
 * Check if a given object implements the StoreTodoResponse interface.
 */
export function instanceOfStoreTodoResponse(value: object): value is StoreTodoResponse {
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("errors" in value) || value["errors"] === undefined) return false;
  return true;
}

export function StoreTodoResponseFromJSON(json: any): StoreTodoResponse {
  return StoreTodoResponseFromJSONTyped(json, false);
}

export function StoreTodoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreTodoResponse {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"],
    errors: StoreTodoValidationErrorFromJSON(json["errors"]),
  };
}

export function StoreTodoResponseToJSON(json: any): StoreTodoResponse {
  return StoreTodoResponseToJSONTyped(json, false);
}

export function StoreTodoResponseToJSONTyped(value?: StoreTodoResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    code: value["code"],
    errors: StoreTodoValidationErrorToJSON(value["errors"]),
  };
}
