/* tslint:disable */
/* eslint-disable */
/**
 * (title)
 * A sample service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface StoreTodoInput
 */
export interface StoreTodoInput {
  /**
   *
   * @type {string}
   * @memberof StoreTodoInput
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof StoreTodoInput
   */
  content: string;
}

/**
 * Check if a given object implements the StoreTodoInput interface.
 */
export function instanceOfStoreTodoInput(value: object): value is StoreTodoInput {
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("content" in value) || value["content"] === undefined) return false;
  return true;
}

export function StoreTodoInputFromJSON(json: any): StoreTodoInput {
  return StoreTodoInputFromJSONTyped(json, false);
}

export function StoreTodoInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreTodoInput {
  if (json == null) {
    return json;
  }
  return {
    title: json["title"],
    content: json["content"],
  };
}

export function StoreTodoInputToJSON(json: any): StoreTodoInput {
  return StoreTodoInputToJSONTyped(json, false);
}

export function StoreTodoInputToJSONTyped(value?: StoreTodoInput | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    title: value["title"],
    content: value["content"],
  };
}
